### ISSUE TITLE
Error message "'templates' directory missing!" but it is there

### ISSUE THREAD

**Issue by Freemason-12** [lah7/Ambiant-MATE-Colours#33]
Tries to build the ambiant mate theme from this repository and got " 'templates' directory missing!" error.
python version 3.8.10
Ubuntu Mate 20.04 LTS.

**Comment by lah7** [comment]
I can't replicate the error, it works on Ubuntu MATE 20.04. This error can only appear if `templates` doesn't exist in the same folder as the script.

What commands did you use?

**Comment by Freemason-12** [comment]
I wrote the command 'python generate-ambiant-mate-colour.py' and then tried a again with --help. Same result. In order for this to work I changed the conditional statement whih drops me there into my own 'templates' directory of the reposiotory, then it worked.
Also, ubuntu-mate-artwork repository does not seem to ship with amibiant mate theme anymore, so I had to take it from root of my system

**Comment by lah7** [comment]
I see - it's because it was ran under the `python` command. This script was designed to run like a regular program `./generate-ambiant-mate-colour.py`. I'll look to support the use case of running via `python` too.

Yes, Ambiant-MATE family of themes has been removed for 22.04, so I have some cleaning up to do for this repository. I have a fork here preserving the history: https://github.com/lah7/Ambiant-MATE/
